### ISSUE TITLE
We seriously need a platform to communicate & share progress

### ISSUE THREAD

**Issue by liginv** [GDGKozhikode/website#1]
In-order to carry forward the **development of the website,** I think we need to communicate & share thoughts **broader than in whatsapp group**; on regular basis. Either make the **slack community** working or **post here in the issues**. Unheard things gradually end-up in undone & unliked.

**Comment by jinur-007** [comment]
@riazek  Can you please get this forward as per the plan we discussed.

**Comment by farishcv** [comment]
@liginv: thanks for the follow up. Invited everyone to our Slack group, please join there and start the conversation on #website-team channel.
